{
  "models": [
    {
      "title": "Gemini 2.5 Flash",
      "provider": "gemini",
      "model": "gemini-2.5-flash",
      "apiKey": "AQ.Ab8RN6Jv9XrNmcyluuu1jFzHhNiGK-zO6pvYiBj6BBLmSjIduw"
    }
  ],
  "tabAutocompleteModel": {
    "title": "Gemini 2.5 Flash",
    "provider": "gemini",
    "model": "gemini-2.5-flash",
    "apiKey": "AQ.Ab8RN6Jv9XrNmcyluuu1jFzHhNiGK-zO6pvYiBj6BBLmSjIduw"
  }
}